 2920970 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2850630 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 3274578 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2878009 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2334638 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 3052849 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2586372 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2752729 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2321506 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
 2746512 : <list index out of range> 
 Traceback (most recent call last):
  File "D:/work/AI_project/proj/prep/vector_file_generation.py", line 55, in generate_csv
    movie_vec = movie_vectorizer.get_vector(movie)
  File "D:\work\AI_project\proj\prep\MovieVector_y.py", line 39, in get_vector
    return [x[1] for x in utils_y.vec_for_movie(self.imdb_conn, movie)]
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 268, in vec_for_movie
    year) + stars_movie_vec(conn, stars, genres, director, year)
  File "D:\work\AI_project\proj\prep\vector_utils_y.py", line 245, in stars_movie_vec
    ("Star_%s avg rating" % i, a_rs[i][0]),
IndexError: list index out of range
 
